const CACHE_NAME='rotina-family-cliente-v64';
const APP_SHELL=['./','./index.html','./index-CLIENTE-v6.html','./manifest.json?v=25','./icon-cliente-192.png','./icon-cliente-512.png','./commercial-access-client.js','./app-monitoring.js','./app-monitoring-extra-v1.js','./client-ui-pro.css','./client-ui-pro.js','./client-mascot-v3.js','./client-mascot-layout-v1.js','./client-cat-asset-v4.js','./client-cat-layout-safe-v5.js','./cat-happy-tiny.webp.b64','./cat-sad-tiny.webp.b64','./cat-happy-tiny.mp3.b64','./cat-sad-tiny.mp3.b64','./client-session-integrity.js','./client-week-nav.js','./family-alarm-client.js','./alarm-schedule-core.js','./client-time-guard-v3.js','./client-history-reconciler.js','./scoring-core.js','./client-reviewed-points.js','./client-early-start-ui.js','./client-tolerance-timer.js','./tolerance-timer-core.js','./client-zero-feedback-v4.js','./latido-cachorro-comemoracao.mp3','./cachorro-triste-choramingo.mp3','./reset-cache.html'];
const MODULE_ROOTS=['https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js','https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js'];
const STATIC_SCRIPTS=['https://cdn.jsdelivr.net/npm/canvas-confetti@1.6.0/dist/confetti.browser.min.js'];
const APP_MAIN_URL=new URL('./index-CLIENTE-v6.html',self.location.href).href;
const ENTRY_URL=new URL('./index.html',self.location.href).href;
const SCOPE_PATH=new URL('./',self.location.href).pathname;
async function cacheModuleTree(url,cache,seen=new Set()){if(seen.has(url))return;seen.add(url);try{const response=await fetch(url,{mode:'cors'});if(!response.ok)return;await cache.put(url,response.clone());const text=await response.text();const specs=[...text.matchAll(/(?:from\s*|import\s*)["']([^"']+)["']/g)].map(m=>m[1]);await Promise.allSettled(specs.map(spec=>{const next=new URL(spec,url).href;return next.startsWith('https://www.gstatic.com/firebasejs/')?cacheModuleTree(next,cache,seen):Promise.resolve();}));}catch(e){console.warn('Cache de módulo indisponível:',url);}}
async function responseWithRequiredAddons(response){if(!response)return response;const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();if(!html.includes('commercial-access-client.js'))html=html.replace('</body>','<script type="module" src="./commercial-access-client.js?v=2"><\/script>\n</body>');if(!html.includes('app-monitoring-extra-v1.js'))html=html.replace('</body>','<script src="./app-monitoring-extra-v1.js?v=3"><\/script>\n</body>');if(!html.includes('client-mascot-layout-v1.js'))html=html.replace('</body>','<script src="./client-mascot-layout-v1.js?v=4"><\/script>\n</body>');if(!html.includes('client-cat-asset-v4.js'))html=html.replace('</body>','<script src="./client-cat-asset-v4.js?v=4"><\/script>\n</body>');if(!html.includes('client-cat-layout-safe-v5.js'))html=html.replace('</body>','<script src="./client-cat-layout-safe-v5.js?v=5"><\/script>\n</body>');const headers=new Headers(response.headers);headers.delete('content-length');return new Response(html,{status:response.status,statusText:response.statusText,headers});}
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE_NAME);await cache.addAll(APP_SHELL);await Promise.allSettled(MODULE_ROOTS.map(url=>cacheModuleTree(url,cache)));await Promise.allSettled(STATIC_SCRIPTS.map(async url=>{try{const r=await fetch(url,{mode:'cors'});if(r.ok)await cache.put(url,r.clone());}catch(e){}}));})());self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)));await self.clients.claim();})());});
async function avisarParadaAlarme(notification){const dados=notification?.data||{};if(dados.tipo!=='alarme-tarefa')return;const janelas=await self.clients.matchAll({type:'window',includeUncontrolled:true});janelas.forEach(janela=>janela.postMessage({type:'ROTINA_FAMILY_ALARM_STOP',tarefaId:dados.tarefaId||'',dataAgendada:dados.dataAgendada||'',ocorrencia:dados.ocorrencia||''}))}
self.addEventListener('notificationclick',event=>{const parar=event.action==='stop-alarm';event.notification.close();event.waitUntil((async()=>{if(parar){await avisarParadaAlarme(event.notification);return}const janelas=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const janela of janelas){if('focus'in janela){await janela.focus();return}}if(self.clients.openWindow)await self.clients.openWindow(event.notification.data?.url||'./')})())});
self.addEventListener('notificationclose',event=>{event.waitUntil(avisarParadaAlarme(event.notification))});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);const staticCdn=(url.hostname==='www.gstatic.com'&&url.pathname.startsWith('/firebasejs/'))||url.hostname==='cdn.jsdelivr.net';const sameOrigin=url.origin===self.location.origin;if(!sameOrigin&&!staticCdn)return;
  if(event.request.mode==='navigate'){
    const entradaLegada=sameOrigin&&(url.pathname===SCOPE_PATH||url.pathname===`${SCOPE_PATH}index.html`);
    event.respondWith((async()=>{
      const alvo=entradaLegada?ENTRY_URL:event.request;
      try{const response=await fetch(alvo,{cache:'no-store'});if(response&&response.ok){const cache=await caches.open(CACHE_NAME);await cache.put(alvo,response.clone());}return url.pathname.endsWith('index-CLIENTE-v6.html')?responseWithRequiredAddons(response):response;}
      catch(e){const cached=(await caches.match(alvo))||(await caches.match(ENTRY_URL))||(await caches.match(APP_MAIN_URL));return url.pathname.endsWith('index-CLIENTE-v6.html')?responseWithRequiredAddons(cached):cached;}
    })());
    return;
  }
  const isAppAsset=sameOrigin&&(/\.(?:js|css|html|json|mp3|b64|webp|png)$/.test(url.pathname));
  if(isAppAsset){event.respondWith((async()=>{try{const response=await fetch(event.request,{cache:'no-store'});if(response&&response.ok){const cache=await caches.open(CACHE_NAME);await cache.put(event.request,response.clone());}return response;}catch(e){return caches.match(event.request);}})());return;}
  event.respondWith((async()=>{const cached=await caches.match(event.request);if(cached)return cached;try{const response=await fetch(event.request);if(response&&(response.ok||response.type==='opaque')){const cache=await caches.open(CACHE_NAME);await cache.put(event.request,response.clone());}return response;}catch(e){throw e;}})());
});