const FIREBASE_API_KEY = 'AIzaSyCP9odEV8TJGOM4lflHk64BbPyXXVjGcYg';

export function testConsoleHtml() {
  return `<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Rotina Family — Teste Comercial Seguro</title>
<style>
:root{font-family:Segoe UI,Tahoma,sans-serif;color:#173a5e;background:#f4f7f6}*{box-sizing:border-box}body{margin:0;padding:14px}.wrap{max-width:980px;margin:auto}.banner{background:#6d28d9;color:#fff;padding:12px 14px;border-radius:14px;margin-bottom:12px;font-weight:800}.note{font-size:12px;line-height:1.45;opacity:.92}.card{background:#fff;border:1px solid #dbe5ef;border-radius:16px;padding:14px;margin:12px 0;box-shadow:0 3px 12px #0000000a}h1,h2,h3{margin:0 0 8px}input,button,select{font:inherit}input{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:9px;margin:5px 0 9px}button{border:0;border-radius:9px;padding:9px 11px;font-weight:800;background:#173a5e;color:#fff;cursor:pointer}button.secondary{background:#475569}button.warn{background:#92400e}button.danger{background:#991b1b}button.safe{background:#166534}.row{display:flex;gap:8px;flex-wrap:wrap}.row>*{flex:1 1 150px}.status{padding:9px;border-radius:9px;background:#f8fafc;border:1px solid #e2e8f0;font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere}.ok{color:#166534}.bad{color:#b91c1c}.muted{color:#64748b}.group{border:1px solid #dbe5ef;border-radius:13px;padding:11px;margin:9px 0;background:#f8fafc}.person{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:9px;margin:6px 0}.pill{display:inline-block;padding:3px 7px;border-radius:999px;background:#ede9fe;color:#5b21b6;font-size:10px;font-weight:800}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:9px}.logs{max-height:420px;overflow:auto}.log{border-bottom:1px solid #edf2f7;padding:8px 2px;font-size:11px}.hidden{display:none}@media(max-width:560px){body{padding:8px}.card{padding:11px}.row{display:grid;grid-template-columns:1fr 1fr}.row>*{min-width:0;font-size:11px}}
</style>
</head>
<body><div class="wrap">
<div class="banner">🧪 TESTE COMERCIAL SEGURO — DRY-RUN<div class="note">Nenhum botão desta tela altera família, perfil ou login. As ações comerciais e administrativas são simuladas no Worker de preview.</div></div>
<div class="card" id="loginCard"><h2>Entrar como ADM Master</h2><div class="note muted">A senha é enviada diretamente do seu navegador ao Firebase Authentication e não passa pelo Worker de teste.</div><label>E-mail</label><input id="email" type="email" autocomplete="username"><label>Senha</label><input id="password" type="password" autocomplete="current-password"><div class="row"><button id="login">Entrar no teste</button><button id="clear" class="secondary">Limpar sessão</button></div><div id="authStatus" class="status muted">Aguardando login.</div></div>
<div id="app" class="hidden">
<div class="card"><h2>Validação</h2><div class="row"><button data-call="session">Validar Master</button><button data-call="users">Usuários</button><button data-call="tree">Árvore</button><button data-call="logs">Logs globais</button></div><div id="apiStatus" class="status muted">Sessão pronta.</div></div>
<div class="card"><h2>Usuários</h2><div class="note muted">Os botões abaixo também são simulação. Não alteram e-mail, senha, estado ou exclusão.</div><div id="users">Ainda não carregado.</div></div>
<div class="card"><h2>🌳 Árvore comercial</h2><div class="note muted">Administrador principal representa a família. Administrador adicional e cliente podem ter bloqueio individual. O Master fica fora do comercial.</div><div id="tree">Ainda não carregada.</div></div>
<div class="card"><h2>🩺 Logs</h2><div class="row"><input id="logGroup" placeholder="SISTEMA ou CLI-XXXX" value="SISTEMA"><button id="loadLogs">Carregar logs</button></div><div id="logs" class="logs">Ainda não carregados.</div></div>
</div></div>
<script>
const API_KEY=${JSON.stringify(FIREBASE_API_KEY)};let token='';let uid='';
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(id,text,ok=true){const el=$(id);el.textContent=text;el.className='status '+(ok?'ok':'bad')}
async function firebaseLogin(email,password){const r=await fetch('https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key='+encodeURIComponent(API_KEY),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error?.message||'Firebase recusou o login');return b}
async function api(path,options={}){if(!token)throw new Error('Entre como Master primeiro.');const r=await fetch(path,{...options,cache:'no-store',headers:{authorization:'Bearer '+token,'content-type':'application/json',...(options.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||('HTTP '+r.status));return b}
$('login').onclick=async()=>{try{status('authStatus','Validando no Firebase…');const b=await firebaseLogin($('email').value.trim(),$('password').value);token=b.idToken||'';uid=b.localId||'';$('password').value='';const s=await api('/admin-master/session');if(s.master!==true)throw new Error('Servidor não confirmou ADM Master.');sessionStorage.setItem('rf_test_token',token);sessionStorage.setItem('rf_test_uid',uid);$('app').classList.remove('hidden');status('authStatus','ADM Master confirmado. Ambiente em dry-run.');status('apiStatus','Master confirmado: '+(s.email||''));}catch(e){token='';uid='';$('app').classList.add('hidden');status('authStatus',e.message,false)}};
$('clear').onclick=()=>{token='';uid='';sessionStorage.removeItem('rf_test_token');sessionStorage.removeItem('rf_test_uid');$('app').classList.add('hidden');status('authStatus','Sessão de teste limpa.');};
async function loadUsers(){const b=await api('/admin-master/users');const users=b.users||[];$('users').innerHTML=users.map(u=>'<div class="person"><strong>'+esc(u.email||'Sem e-mail')+'</strong> '+(u.papel==='master'?'<span class="pill">MASTER</span>':'')+'<div class="muted">'+esc(u.grupoId||'—')+' · '+esc(u.papel||'')+' · '+(u.desativado?'desativado':'ativo')+'</div>'+(u.papel==='master'?'':'<div class="row" style="margin-top:6px"><button class="warn" data-user-action="set-disabled" data-uid="'+esc(u.uid)+'">Simular desativar login</button><button class="danger" data-user-action="delete-user" data-uid="'+esc(u.uid)+'">Simular excluir login</button></div>')+'</div>').join('')||'Nenhum usuário.';return users}
async function loadTree(){const b=await api('/admin-master/tree');const groups=b.groups||[];$('tree').innerHTML=groups.map(g=>'<section class="group"><div><strong>'+esc(g.grupoId)+'</strong> <span class="pill">'+esc(g.estado||'')+'</span></div>'+(g.contemMasterLegado?'<div class="muted">🔐 Há vínculo legado do Master, mas ele fica fora do comercial.</div>':'')+'<div class="row" style="margin:7px 0"><button class="warn" data-group="'+esc(g.grupoId)+'" data-block="'+(!g.grupoBloqueado)+'">'+(g.grupoBloqueado?'Simular liberar família':'Simular bloquear família')+'</button><button class="secondary" data-group-logs="'+esc(g.grupoId)+'">Logs do grupo</button></div><h3>Administradores</h3>'+(g.administradores||[]).map(a=>'<div class="person"><strong>'+(a.principal?'👑 ':'🛡️ ')+esc(a.email||'Administrador')+'</strong> '+(a.master?'<span class="pill">MASTER</span>':'')+'<div class="muted">'+(a.principal?'principal':'adicional')+(a.bloqueadoComercialIndividual?' · bloqueio comercial':'')+'</div>'+(!a.master&&!a.principal?'<button class="warn" data-admin="'+esc(a.uid)+'" data-admin-block="'+(!a.bloqueadoComercialIndividual)+'">'+(a.bloqueadoComercialIndividual?'Simular liberar admin':'Simular bloquear admin')+'</button>':'')+'</div>').join('')+'<h3>Clientes</h3>'+(g.clientes||[]).map(p=>'<div class="person"><strong>👤 '+esc(p.nome||'Cliente')+'</strong><div class="muted">'+esc(p.perfilId||p.id||'')+(p.desativado?' · bloqueado':'')+'</div><button class="warn" data-profile="'+esc(p.id)+'" data-profile-block="'+(!p.desativado)+'">'+(p.desativado?'Simular liberar cliente':'Simular bloquear cliente')+'</button></div>').join('')+'</section>').join('')||'Nenhuma família encontrada.';return groups}
async function loadLogs(group=$('logGroup').value.trim()||'SISTEMA'){const b=await api('/admin-master/logs?grupoId='+encodeURIComponent(group));const logs=b.logs||[];$('logs').innerHTML=logs.map(l=>'<div class="log"><strong>'+esc(l.evento||'evento')+'</strong> · '+esc(l.grupoId||'—')+' · '+esc(l.aplicativo||'')+' · '+esc(l.nivel||'')+'<br>'+esc(l.clienteEm||'')+'</div>').join('')||'<div class="muted">Nenhum log retornado.</div>';return logs}
$('loadLogs').onclick=()=>loadLogs().then(l=>status('apiStatus','Logs carregados: '+l.length)).catch(e=>status('apiStatus',e.message,false));
document.querySelector('[data-call="session"]').onclick=()=>api('/admin-master/session').then(b=>status('apiStatus','Master: '+b.master+' · '+(b.email||''))).catch(e=>status('apiStatus',e.message,false));
document.querySelector('[data-call="users"]').onclick=()=>loadUsers().then(v=>status('apiStatus','Usuários carregados: '+v.length)).catch(e=>status('apiStatus',e.message,false));
document.querySelector('[data-call="tree"]').onclick=()=>loadTree().then(v=>status('apiStatus','Famílias carregadas: '+v.length)).catch(e=>status('apiStatus',e.message,false));
document.querySelector('[data-call="logs"]').onclick=()=>{ $('logGroup').value='SISTEMA';loadLogs('SISTEMA').then(v=>status('apiStatus','Logs globais: '+v.length)).catch(e=>status('apiStatus',e.message,false));};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{let result=null;if(b.dataset.group){result=await api('/admin-master/groups',{method:'POST',body:JSON.stringify({action:'set-group-blocked',grupoId:b.dataset.group,disabled:b.dataset.block==='true'})})}else if(b.dataset.admin){result=await api('/admin-master/admin-access',{method:'POST',body:JSON.stringify({action:'set-admin-commercial-block',targetUid:b.dataset.admin,disabled:b.dataset.adminBlock==='true'})})}else if(b.dataset.profile){result=await api('/admin-master/profiles',{method:'POST',body:JSON.stringify({action:'set-profile-disabled',profileId:b.dataset.profile,disabled:b.dataset.profileBlock==='true'})})}else if(b.dataset.userAction){result=await api('/admin-master/users',{method:'POST',body:JSON.stringify({action:b.dataset.userAction,targetUid:b.dataset.uid,disabled:true})})}else if(b.dataset.groupLogs){$('logGroup').value=b.dataset.groupLogs;const logs=await loadLogs(b.dataset.groupLogs);status('apiStatus','Logs de '+b.dataset.groupLogs+': '+logs.length);return}if(result)status('apiStatus',(result.message||'Simulação concluída')+' · dryRun='+String(result.dryRun===true));}catch(err){status('apiStatus',err.message,false)}});
const saved=sessionStorage.getItem('rf_test_token');if(saved){token=saved;uid=sessionStorage.getItem('rf_test_uid')||'';api('/admin-master/session').then(s=>{if(s.master){$('app').classList.remove('hidden');status('authStatus','Sessão de teste restaurada para '+(s.email||''));}}).catch(()=>{sessionStorage.removeItem('rf_test_token');sessionStorage.removeItem('rf_test_uid');token='';});}
</script></body></html>`;
}
