const FIREBASE_API_KEY = 'AIzaSyCP9odEV8TJGOM4lflHk64BbPyXXVjGcYg';
const MASTER_EMAIL = 'paes2005@gmail.com';

export function testConsoleHtml() {
  return `<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Rotina Family — Teste da arquitetura original</title>
<style>
:root{font-family:Segoe UI,Tahoma,sans-serif;color:#173a5e;background:#f4f7f6}*{box-sizing:border-box}body{margin:0;padding:10px}.wrap{max-width:820px;margin:auto}.banner{background:#6d28d9;color:#fff;padding:12px 14px;border-radius:14px;margin-bottom:10px;font-weight:800}.note{font-size:12px;line-height:1.45}.card{background:#fff;border:1px solid #dbe5ef;border-radius:16px;padding:13px;margin:10px 0;box-shadow:0 3px 12px #0000000a}h2,h3{margin:0 0 8px}input,button,select{font:inherit}input,select{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:9px;margin:5px 0 9px;background:#fff}button{border:0;border-radius:9px;padding:10px 11px;font-weight:800;background:#173a5e;color:#fff;cursor:pointer}button.warn{background:#92400e}button.safe{background:#166534}button.secondary{background:#475569}.row{display:flex;gap:8px;flex-wrap:wrap}.row>*{flex:1 1 150px}.status{padding:9px;border-radius:9px;background:#f8fafc;border:1px solid #e2e8f0;font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere}.ok{color:#166534}.bad{color:#b91c1c}.muted{color:#64748b}.person{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:9px;margin:6px 0}.group{border:1px solid #dbe5ef;border-radius:13px;padding:11px;margin-top:9px;background:#f8fafc}.pill{display:inline-block;padding:3px 7px;border-radius:999px;background:#ede9fe;color:#5b21b6;font-size:10px;font-weight:800}.hidden{display:none}.filters{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.logs{max-height:440px;overflow:auto;border:1px solid #e2e8f0;border-radius:10px;margin-top:9px}.log{border-bottom:1px solid #edf2f7;padding:9px;font-size:11px}.log.error{background:#fff1f2}.log.warning{background:#fffbeb}@media(max-width:560px){.row,.filters{display:grid;grid-template-columns:1fr}.row>*{min-width:0}}
</style>
</head>
<body><div class="wrap">
<div class="banner">🧪 TESTE — ARQUITETURA ORIGINAL<div class="note">Árvore comercial e monitoramento são módulos independentes. O Master nunca participa do bloqueio comercial.</div></div>
<div class="card"><h2>ADM Master</h2><div class="note muted">Login Master fixo: ${MASTER_EMAIL}</div><label>E-mail</label><input id="email" type="email" value="${MASTER_EMAIL}" readonly autocomplete="username"><label>Senha</label><input id="password" type="password" autocomplete="current-password"><button id="login">Entrar no teste</button><div id="authStatus" class="status muted">Aguardando login.</div></div>
<div id="app" class="hidden">
<div class="card"><h2>🌳 Grupos familiares</h2><div class="note muted">Mostra todas as famílias. Cada grupo é identificado pelo CLI e pelo e-mail do administrador principal. Ao abrir, aparecem os integrantes daquele grupo. O único controle comercial desta fase é bloquear/liberar o grupo inteiro.</div><input id="groupSearch" placeholder="Pesquisar CLI ou e-mail do administrador principal"><select id="groupSelect"><option value="">Carregando grupos…</option></select><div class="row"><button id="refreshGroups" class="secondary">Atualizar grupos</button><button id="openGroup">Abrir grupo</button></div><div id="groupsStatus" class="status muted">Aguardando lista de grupos.</div><div id="group"></div></div>
<div class="card"><h2>🩺 Monitoramento e logs</h2><div class="note muted">Diagnóstico do aplicativo inteiro: Cliente, ADM, Master, sincronização, alarmes/despertador, notificações, rede, erros e ações instrumentadas. O grupo é apenas um filtro.</div><div class="filters"><select id="logGroup"><option value="SISTEMA">Todos os grupos</option></select><select id="logApp"><option value="">Todos os aplicativos</option><option value="cliente">Cliente</option><option value="adm">ADM</option><option value="master">Master</option></select><select id="logLevel"><option value="">Todos os níveis</option><option value="error">Erros</option><option value="warning">Avisos</option><option value="info">Informações</option></select></div><button id="loadLogs">Carregar logs</button><div id="logsStatus" class="status muted" style="margin-top:8px">Nenhum log consultado nesta sessão.</div><div id="logs" class="logs"><div class="log muted">O carregamento é manual para não gerar leituras desnecessárias.</div></div></div>
</div></div>
<script>
const API_KEY=${JSON.stringify(FIREBASE_API_KEY)};const MASTER=${JSON.stringify(MASTER_EMAIL)};let token='';let allGroups=[];let currentGroup='';let cachedLogs=[];
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function status(id,text,ok=true){const el=$(id);el.textContent=text;el.className='status '+(ok?'ok':'bad')}
async function firebaseLogin(email,password){if(String(email||'').trim().toLowerCase()!==MASTER)throw new Error('Use o login ADM Master definido para este teste.');const r=await fetch('https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key='+encodeURIComponent(API_KEY),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error?.message||'Firebase recusou o login');return b}
async function api(path,options={}){if(!token)throw new Error('Entre como Master primeiro.');const r=await fetch(path,{...options,cache:'no-store',headers:{authorization:'Bearer '+token,'content-type':'application/json',...(options.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||('HTTP '+r.status));return b}
function selectedRecord(){const id=$('groupSelect').value;return allGroups.find(g=>g.grupoId===id)||null}
function syncGroupFilters(){const selected=$('logGroup').value||'SISTEMA';$('logGroup').innerHTML='<option value="SISTEMA">Todos os grupos</option>'+allGroups.map(g=>'<option value="'+esc(g.grupoId)+'">'+esc(g.grupoId)+'</option>').join('');$('logGroup').value=allGroups.some(g=>g.grupoId===selected)?selected:'SISTEMA'}
function renderGroupOptions(){const term=String($('groupSearch').value||'').trim().toLowerCase();const current=$('groupSelect').value;const filtered=allGroups.filter(g=>!term||String(g.grupoId).toLowerCase().includes(term)||String(g.proprietarioEmail||'').toLowerCase().includes(term));$('groupSelect').innerHTML='<option value="">Escolha um grupo familiar</option>'+filtered.map(g=>'<option value="'+esc(g.grupoId)+'">'+esc(g.grupoId)+' — '+esc(g.proprietarioEmail||'proprietário sem e-mail')+'</option>').join('');if(filtered.some(g=>g.grupoId===current))$('groupSelect').value=current;syncGroupFilters()}
async function loadGroups(){try{status('groupsStatus','Carregando todos os grupos familiares…');const b=await api('/admin-master/groups');allGroups=b.groups||[];renderGroupOptions();status('groupsStatus',(b.aviso?b.aviso+' · ':'')+allGroups.length+' grupo(s) encontrado(s).');}catch(e){allGroups=[];renderGroupOptions();status('groupsStatus',e.message,false)}}
function renderGroup(g,ownerHint){const owner=g.administradorPrincipal||ownerHint||null;const admins=g.administradores||[];const clients=g.clientes||[];const guests=admins.filter(a=>!a.principal&&!a.master);const masterLegacy=admins.filter(a=>a.master);const commercial=g.statusComercialDisponivel===false?'STATUS INDISPONÍVEL':(g.grupoBloqueado?'BLOQUEADO':'ATIVO');const warning=(g.avisos||[]).length?'<div class="status bad" style="margin-top:8px">Leitura parcial: '+esc((g.avisos||[]).join(' · '))+'</div>':'';$('group').innerHTML='<section class="group"><div><strong style="font-size:16px">🌳 '+esc(g.grupoId)+'</strong> <span class="pill">'+esc(commercial)+'</span></div><div class="person" style="margin-top:9px"><strong>👑 Administrador principal</strong><div>'+esc(owner?.email||'Não identificado')+'</div></div>'+(guests.length?'<h3>Administradores convidados</h3>'+guests.map(a=>'<div class="person">🛡️ '+esc(a.email||'Administrador')+'</div>').join(''):'<div class="muted">Nenhum administrador convidado retornado.</div>')+(clients.length?'<h3>Integrantes da família</h3>'+clients.map(p=>'<div class="person">👤 '+esc(p.nome||'Integrante')+' <span class="muted">'+esc(p.perfilId||'')+'</span></div>').join(''):'<div class="muted">Nenhum integrante retornado.</div>')+(masterLegacy.length?'<div class="note muted">🔐 Há vínculo legado do Master neste CLI, mas ele fica fora do comercial.</div>':'')+warning+'<div class="row" style="margin-top:10px"><button class="'+(g.grupoBloqueado?'safe':'warn')+'" id="toggleGroup">'+(g.grupoBloqueado?'Simular liberar grupo':'Simular bloquear grupo')+'</button></div></section>';const btn=$('toggleGroup');btn.onclick=()=>simulateGroupBlock(g.grupoId,!g.grupoBloqueado)}
async function openSelectedGroup(){const selected=selectedRecord();if(!selected){status('groupsStatus','Escolha um grupo na lista.',false);return}try{currentGroup=selected.grupoId;status('groupsStatus','Abrindo '+currentGroup+'…');const path='/admin-master/group?grupoId='+encodeURIComponent(currentGroup)+'&ownerEmail='+encodeURIComponent(selected.proprietarioEmail||'');const b=await api(path);renderGroup(b.grupo||{}, {email:selected.proprietarioEmail||''});status('groupsStatus',(b.grupo?.parcial?'Grupo carregado parcialmente: ':'Grupo carregado: ')+currentGroup,!b.grupo?.parcial);}catch(e){$('group').innerHTML='';status('groupsStatus',e.message,false)}}
async function simulateGroupBlock(group,disabled){try{const r=await api('/admin-master/groups',{method:'POST',body:JSON.stringify({action:'set-group-blocked',grupoId:group,disabled})});status('groupsStatus',(r.message||'Simulação concluída')+' · dryRun='+String(r.dryRun===true));}catch(e){status('groupsStatus',e.message,false)}}
function detailsText(details){if(!details||typeof details!=='object')return '';return Object.entries(details).map(([k,v])=>k+': '+String(v)).join(' · ')}
function renderLogs(){const app=$('logApp').value;const level=$('logLevel').value;const logs=cachedLogs.filter(l=>(!app||l.aplicativo===app)&&(!level||l.nivel===level));$('logs').innerHTML=logs.map(l=>'<div class="log '+esc(l.nivel||'info')+'"><strong>'+esc(l.evento||'evento')+'</strong> · '+esc(l.grupoId||'—')+' · '+esc(l.aplicativo||'')+' · '+esc(l.nivel||'info')+'<br><span class="muted">'+esc(l.clienteEm||'')+' · '+esc(detailsText(l.detalhes))+'</span></div>').join('')||'<div class="log muted">Nenhum log encontrado para os filtros selecionados.</div>'}
async function loadLogs(){const group=$('logGroup').value||'SISTEMA';try{status('logsStatus',group==='SISTEMA'?'Carregando logs de todos os grupos…':'Carregando logs de '+group+'…');const b=await api('/admin-master/logs?grupoId='+encodeURIComponent(group));cachedLogs=b.logs||[];renderLogs();status('logsStatus',cachedLogs.length+' log(s) carregado(s) · escopo: '+(b.escopo||group));}catch(e){cachedLogs=[];$('logs').innerHTML='<div class="log bad">'+esc(e.message||e)+'</div>';status('logsStatus',e.message,false)}}
$('login').onclick=async()=>{try{status('authStatus','Validando Master…');const b=await firebaseLogin($('email').value,$('password').value);token=b.idToken||'';$('password').value='';const s=await api('/admin-master/session');if(s.master!==true||String(s.email||'').toLowerCase()!==MASTER)throw new Error('Servidor não confirmou o ADM Master esperado.');$('app').classList.remove('hidden');status('authStatus','ADM Master confirmado: '+MASTER);await loadGroups();}catch(e){token='';$('app').classList.add('hidden');status('authStatus',e.message,false)}};
$('groupSearch').oninput=renderGroupOptions;$('refreshGroups').onclick=loadGroups;$('openGroup').onclick=openSelectedGroup;$('groupSelect').onchange=()=>{if($('groupSelect').value)openSelectedGroup();};$('loadLogs').onclick=loadLogs;$('logApp').onchange=renderLogs;$('logLevel').onchange=renderLogs;
</script></body></html>`;
}
