const FIREBASE_API_KEY = 'AIzaSyCP9odEV8TJGOM4lflHk64BbPyXXVjGcYg';
const MASTER_EMAIL = 'paes2005@gmail.com';

export function testConsoleHtml() {
  return `<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Rotina Family — Teste por Grupo</title>
<style>
:root{font-family:Segoe UI,Tahoma,sans-serif;color:#173a5e;background:#f4f7f6}*{box-sizing:border-box}body{margin:0;padding:10px}.wrap{max-width:760px;margin:auto}.banner{background:#6d28d9;color:#fff;padding:12px 14px;border-radius:14px;margin-bottom:10px;font-weight:800}.note{font-size:12px;line-height:1.45}.card{background:#fff;border:1px solid #dbe5ef;border-radius:16px;padding:13px;margin:10px 0;box-shadow:0 3px 12px #0000000a}h2,h3{margin:0 0 8px}input,button{font:inherit}input{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:9px;margin:5px 0 9px}button{border:0;border-radius:9px;padding:10px 11px;font-weight:800;background:#173a5e;color:#fff;cursor:pointer}button.warn{background:#92400e}button.safe{background:#166534}.row{display:flex;gap:8px;flex-wrap:wrap}.row>*{flex:1 1 150px}.status{padding:9px;border-radius:9px;background:#f8fafc;border:1px solid #e2e8f0;font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere}.ok{color:#166534}.bad{color:#b91c1c}.muted{color:#64748b}.person{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:9px;margin:6px 0}.group{border:1px solid #dbe5ef;border-radius:13px;padding:11px;margin-top:9px;background:#f8fafc}.pill{display:inline-block;padding:3px 7px;border-radius:999px;background:#ede9fe;color:#5b21b6;font-size:10px;font-weight:800}.hidden{display:none}.logs{max-height:320px;overflow:auto}.log{border-bottom:1px solid #edf2f7;padding:8px 2px;font-size:11px}@media(max-width:560px){.row{display:grid;grid-template-columns:1fr 1fr}.row>*{min-width:0;font-size:11px}}
</style>
</head>
<body><div class="wrap">
<div class="banner">🧪 TESTE COMERCIAL SEGURO — POR GRUPO<div class="note">Fase atual: consultar e simular bloqueio da família inteira. Sem bloqueios individuais.</div></div>
<div class="card"><h2>ADM Master</h2><div class="note muted">O único Master deste teste é ${MASTER_EMAIL}. Ele fica fora de qualquer bloqueio de grupo.</div><label>E-mail</label><input id="email" type="email" value="${MASTER_EMAIL}" autocomplete="username"><label>Senha</label><input id="password" type="password" autocomplete="current-password"><button id="login">Entrar no teste</button><div id="authStatus" class="status muted">Aguardando login.</div></div>
<div id="app" class="hidden">
<div class="card"><h2>Grupo familiar</h2><div class="note muted">Informe somente o código da família. Ex.: CLI-6148.</div><input id="groupCode" placeholder="CLI-0000" autocapitalize="characters"><div class="row"><button id="loadGroup">Consultar grupo</button><button id="loadGroupLogs">Logs deste grupo</button></div><div id="groupStatus" class="status muted">Nenhum grupo consultado.</div><div id="group"></div></div>
<div class="card"><h2>🩺 Logs</h2><div class="note muted">Os logs continuam separados do bloqueio comercial.</div><div id="logs" class="logs">Selecione um grupo e toque em “Logs deste grupo”.</div></div>
</div></div>
<script>
const API_KEY=${JSON.stringify(FIREBASE_API_KEY)};const MASTER=${JSON.stringify(MASTER_EMAIL)};let token='';let currentGroup='';
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(id,text,ok=true){const el=$(id);el.textContent=text;el.className='status '+(ok?'ok':'bad')}
async function firebaseLogin(email,password){if(String(email||'').trim().toLowerCase()!==MASTER)throw new Error('Use o login ADM Master definido para este teste.');const r=await fetch('https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key='+encodeURIComponent(API_KEY),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error?.message||'Firebase recusou o login');return b}
async function api(path,options={}){if(!token)throw new Error('Entre como Master primeiro.');const r=await fetch(path,{...options,cache:'no-store',headers:{authorization:'Bearer '+token,'content-type':'application/json',...(options.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||('HTTP '+r.status));return b}
$('login').onclick=async()=>{try{status('authStatus','Validando Master…');const b=await firebaseLogin($('email').value,$('password').value);token=b.idToken||'';$('password').value='';const s=await api('/admin-master/session');if(s.master!==true||String(s.email||'').toLowerCase()!==MASTER)throw new Error('Servidor não confirmou o ADM Master esperado.');$('app').classList.remove('hidden');status('authStatus','ADM Master confirmado: '+MASTER);}catch(e){token='';$('app').classList.add('hidden');status('authStatus',e.message,false)}};
function normalizeGroup(){return String($('groupCode').value||'').trim().toUpperCase()}
function renderGroup(g){const owner=g.administradorPrincipal;const admins=g.administradores||[];const clients=g.clientes||[];const guests=admins.filter(a=>!a.principal&&!a.master);const masterLegacy=admins.filter(a=>a.master);$('group').innerHTML='<section class="group"><div><strong style="font-size:16px">🌳 '+esc(g.grupoId)+'</strong> <span class="pill">'+(g.grupoBloqueado?'BLOQUEADO':'ATIVO')+'</span></div><div class="person" style="margin-top:9px"><strong>👑 Administrador principal</strong><div>'+esc(owner?.email||'Não identificado')+'</div></div>'+(guests.length?'<h3>Administradores convidados</h3>'+guests.map(a=>'<div class="person">🛡️ '+esc(a.email||'Administrador')+'</div>').join(''):'')+(clients.length?'<h3>Integrantes da família</h3>'+clients.map(p=>'<div class="person">👤 '+esc(p.nome||'Integrante')+' <span class="muted">'+esc(p.perfilId||'')+'</span></div>').join(''):'<div class="muted">Nenhum cliente/perfil encontrado neste grupo.</div>')+(masterLegacy.length?'<div class="note muted">🔐 Existe vínculo legado do Master neste CLI, mas ele não participa do bloqueio comercial.</div>':'')+'<div class="row" style="margin-top:10px"><button class="'+(g.grupoBloqueado?'safe':'warn')+'" id="toggleGroup">'+(g.grupoBloqueado?'Simular liberar grupo':'Simular bloquear grupo')+'</button></div></section>';const btn=$('toggleGroup');btn.onclick=()=>simulateGroupBlock(g,!g.grupoBloqueado)}
async function loadGroup(){const group=normalizeGroup();if(!group){status('groupStatus','Informe o código do grupo.',false);return}try{status('groupStatus','Consultando apenas '+group+'…');const b=await api('/admin-master/group?grupoId='+encodeURIComponent(group));currentGroup=group;renderGroup(b.grupo||{});status('groupStatus','Grupo carregado: '+group);}catch(e){$('group').innerHTML='';status('groupStatus',e.message,false)}}
async function simulateGroupBlock(group,disabled){try{const r=await api('/admin-master/groups',{method:'POST',body:JSON.stringify({action:'set-group-blocked',grupoId:group,disabled})});status('groupStatus',(r.message||'Simulação concluída')+' · dryRun='+String(r.dryRun===true));}catch(e){status('groupStatus',e.message,false)}}
async function loadLogs(){const group=normalizeGroup()||currentGroup;if(!group){$('logs').innerHTML='<div class="bad">Selecione um grupo primeiro.</div>';return}try{$('logs').innerHTML='<div class="muted">Carregando logs de '+esc(group)+'…</div>';const b=await api('/admin-master/logs?grupoId='+encodeURIComponent(group));const logs=b.logs||[];$('logs').innerHTML=logs.map(l=>'<div class="log"><strong>'+esc(l.evento||'evento')+'</strong> · '+esc(l.aplicativo||'')+' · '+esc(l.nivel||'')+'<br>'+esc(l.clienteEm||'')+'</div>').join('')||'<div class="muted">Nenhum log retornado para este grupo.</div>';}catch(e){$('logs').innerHTML='<div class="bad">'+esc(e.message||e)+'</div>'}}
$('loadGroup').onclick=loadGroup;$('loadGroupLogs').onclick=loadLogs;
</script></body></html>`;
}
